// 句型模式內容(來源:林茂松《英文句型》— 5 基本句 + 110 應用句型)。
// 基本句型 = 五大基本句;應用句型 = 110 常見句型。操練:看句型公式 → 跟讀/說出例句 → 比對。

export type SentencePattern = { id: string; pattern: string; zh?: string; tags: string[]; examples: string[] };

// ── 基本句型(五大基本句)──
export const SP_BASIC: SentencePattern[] = [
  { id: "B1", pattern: "S + V(i)", zh: "主詞 + 不及物動詞", tags: ["simple"], examples: ["Time flies.", "He usually gets up early in the morning.", "John is talking aloud."] },
  { id: "B2", pattern: "S + V(i) + SC", zh: "主詞 + 不及物動詞 + 主詞補語", tags: ["simple"], examples: ["Miss Liu is my English teacher.", "The leaves turn red in autumn.", "To see is to believe."] },
  { id: "B3", pattern: "S + V(t) + O", zh: "主詞 + 及物動詞 + 受詞", tags: ["simple"], examples: ["Boys and girls played soccer for fun and health.", "Bill always makes his own bed.", "Our math teacher likes to play chess."] },
  { id: "B4", pattern: "S + V(t) + IO + DO", zh: "主詞 + 及物動詞 + 間接受詞 + 直接受詞", tags: ["simple"], examples: ["My boyfriend gave me roses as my birthday present.", "I wrote my brother a letter last Sunday.", "Would you please pass me the salt?"] },
  { id: "B5", pattern: "S + V(t) + O + OC", zh: "主詞 + 及物動詞 + 受詞 + 受詞補語", tags: ["simple"], examples: ["I consider you my best friend.", "The bad news made us unhappy.", "Helen sometimes leaves her son alone at home."] },
];

// ── 應用句型(110 個常見句型)──
export const SP_APPLIED: SentencePattern[] = [
  { id: "A1", pattern: "All one has to do is + V", tags: ["emphasis"], examples: ["All he has to do is fill out a form.", "All he had to do was become friends with the people and their chief."] },
  { id: "A2", pattern: "Although ..., ...", tags: ["concession", "clause"], examples: ["Although Jacky Cheung is a Hong Kong singer, he is popular in Taiwan, too.", "Although Hsieh was handicapped, he looked truly happy."] },
  { id: "A3", pattern: "as ... as possible", tags: ["comparison"], examples: ["Come as quickly as possible.", "Run as fast as possible."] },
  { id: "A4", pattern: "as if / as though", tags: ["clause"], examples: ["You look as if you've had a good time.", "It sounds as though she's been really ill."] },
  { id: "A5", pattern: "As soon as + S1 + V1..., S2 + V2...", tags: ["time", "clause"], examples: ["He left as soon as he heard the news.", "I'll tell him as soon as I see him."] },
  { id: "A6", pattern: "as / so far as ... be concerned", tags: ["idiom"], examples: ["As far as I am concerned, you can do what you like.", "As far as I am concerned, the whole idea is crazy."] },
  { id: "A7", pattern: "Be / Feel + adj. + to V", tags: ["infinitive"], examples: ["Most Americans will be happy to explain.", "I feel sad to know he is leaving us for good."] },
  { id: "A8", pattern: "be / get used to + N / V-ing", tags: ["gerund", "idiom"], examples: ["He is used to working hard.", "The food in England is strange at first, but you'll soon get used to it."] },
  { id: "A9", pattern: "Because + S + V ... / Because of + N, S + V", tags: ["reason", "clause"], examples: ["I am eating like a horse because I am very hungry.", "The audience booed the actors because they gave a bad performance.", "Because of ill health, he had to retire."] },
  { id: "A10", pattern: "both ... and ...", tags: ["conjunction"], examples: ["He's lived in both Britain and America.", "She can both speak and write Japanese."] },
  { id: "A11", pattern: "..., but ...", tags: ["conjunction"], examples: ["Cheung is successful and rich today, but he chooses to live a simple life.", "Hsieh could only paint by holding the brush in his teeth, but it still brought him great happiness."] },
  { id: "A12", pattern: "But for / But that ...", tags: ["subjunctive"], examples: ["But that you had seen me in the water, I would have drowned.", "But for the rain, we would have had a nice holiday."] },
  { id: "A13", pattern: "By + V-ing ...", tags: ["gerund"], examples: ["He made his money by buying and selling houses.", "You can turn on the radio by pressing this button."] },
  { id: "A14", pattern: "S + cannot but + V", tags: ["idiom"], examples: ["It was a rash thing to do, yet one cannot but admire her courage.", "I could not but admit that he was right and I was wrong."] },
  { id: "A15", pattern: "Comparatives (比較級)", tags: ["comparison"], examples: ["The apartment in Hsinchu is more spacious than the one we have in Taipei.", "John is older than Jean."] },
  { id: "A16", pattern: "either ... or ...", tags: ["conjunction"], examples: ["I left it either on the table or in the drawer.", "You can either write or phone to request a copy."] },
  { id: "A17", pattern: "enjoy / finish / mind / practice + V-ing", tags: ["gerund"], examples: ["Do you mind opening the window?", "They enjoy talking with people, even in broken English."] },
  { id: "A18", pattern: "Even if / Even though + S1 + V1, S2 + V2", tags: ["concession", "clause"], examples: ["Even if I have to walk all the way, I'll get there.", "I like her even though she can be annoying."] },
  { id: "A19", pattern: "far from ...", tags: ["idiom"], examples: ["Far from enjoying dancing, he loathes it.", "Your account is far from the truth."] },
  { id: "A20", pattern: "find it + O.C. + to V", tags: ["infinitive"], examples: ["She found it difficult to understand him.", "At my age I would find it hard to get another job."] },
  { id: "A21", pattern: "For example, ...", tags: ["transition"], examples: ["Dogs can be very helpful. For example, many people keep dogs as pets.", "Joe often does selfish things. For example, he never shares anything of his own with others."] },
  { id: "A22", pattern: "get / have + O + V-p.p.", tags: ["causative"], examples: ["They're going to have their house painted.", "Go and get your hair cut!"] },
  { id: "A23", pattern: "Given ...", tags: ["idiom"], examples: ["Given the government's record on unemployment, their chances of winning the election look poor.", "Given that she is interested in children, I am sure teaching is the right career for her."] },
  { id: "A24", pattern: "Hardly / Scarcely + had + S1 + V1-en ... when / before + S2 + V2-ed", tags: ["inversion", "time"], examples: ["Hardly had we begun our walk when it began to rain.", "Scarcely had she entered the room when the phone rang."] },
  { id: "A25", pattern: "How + adj.!", tags: ["exclamation"], examples: ["How impractical!", "You can just take out your credit card and charge it. How convenient!"] },
  { id: "A26", pattern: "How + adj. + (it is) + to V / How + adj./adv. + S + V!", tags: ["exclamation"], examples: ["How nice it is to have a rose garden!", "How tiring it is to work part time while studying full time!", "How beautiful she is!"] },
  { id: "A27", pattern: "How many / How much ...", tags: ["question"], examples: ["How many kids do they have now?", "How much is that sweater, the blue one?"] },
  { id: "A28", pattern: "How about / What about ...?", tags: ["question"], examples: ["How about going for a walk?", "How about going to a movie this evening?"] },
  { id: "A29", pattern: "I + want / like / plan + to V", tags: ["infinitive"], examples: ["I want to hold your hand.", "We're planning to visit France this summer."] },
  { id: "A30", pattern: "I wish + S + 過去式/過去完成式", tags: ["subjunctive"], examples: ["I wish you hadn't told me all this.", "I wish I knew what was going to happen."] },
  { id: "A31", pattern: "If / Whether ... (名詞子句)", tags: ["clause"], examples: ["I am not sure whether he will arrive on time (or not).", "I have no idea if he is the right person for the job."] },
  { id: "A32", pattern: "If + S + V..., S + V...", tags: ["conditional"], examples: ["If you feel sad or afraid, try wearing something orange.", "If it rains tomorrow, I won't go."] },
  { id: "A33", pattern: "If + S + V-ed, S + would ... (與現在事實相反)", tags: ["conditional", "subjunctive"], examples: ["If I were you, I might marry him.", "If I had a robot, I would ask it to help me with my lessons."] },
  { id: "A34", pattern: "If + S1 + V1..., S2 + V2...", tags: ["conditional"], examples: ["I'll only stay if you offer me more money.", "You can stay to dinner if you like."] },
  { id: "A35", pattern: "If only ...", tags: ["subjunctive"], examples: ["If only I were rich.", "If only I knew her name."] },
  { id: "A36", pattern: "If 的省略 (倒裝)", tags: ["conditional", "inversion"], examples: ["Had he written that letter, she wouldn't have made this mistake.", "Should it rain tomorrow, I would stay home."] },
  { id: "A37", pattern: "In other words / Furthermore, ... S + V", tags: ["transition"], examples: ["In other words, the objective is to avoid losing.", "Furthermore, my aim is to provide the best service possible under these difficult circumstances."] },
  { id: "A38", pattern: "Indirect speech (間接引述)", tags: ["clause"], examples: ["The girl said that they were going to Florida.", "Father told me that he was disappointed in me."] },
  { id: "A39", pattern: "Instead of + V-ing / N, S + V...", tags: ["gerund"], examples: ["Let's play cards instead of watching television.", "Instead of Tom, it was Peter who moved in."] },
  { id: "A40", pattern: "Instead, ...", tags: ["transition"], examples: ["Don't marry Phil; marry me instead.", "Peter did not join the army; instead, he decided to become a painter."] },
  { id: "A41", pattern: "It (so) happens that ...", tags: ["it-pattern"], examples: ["It happened that she was out when he called.", "It happened that the new person in the office was the woman he had met at Gail's party."] },
  { id: "A42", pattern: "It + takes / took + sb + time + to V", tags: ["it-pattern", "infinitive"], examples: ["It took her three hours to mend her bicycle.", "It took us half an hour to get there."] },
  { id: "A43", pattern: "It appears / seems that ...", tags: ["it-pattern"], examples: ["It appears that there has been a change in the plans.", "It seems that the attack this morning was very carefully planned."] },
  { id: "A44", pattern: "It costs (sb) + 錢 + to V", tags: ["it-pattern", "infinitive"], examples: ["It costs them 1000 pounds a year to run a car.", "It's going to cost me over $100,000 to buy new trucks."] },
  { id: "A45", pattern: "It is (was) ... that ... (最高級 + 經驗)", tags: ["emphasis", "comparison"], examples: ["It was the best coffee that I have ever tasted.", "It was the funniest joke that I have ever heard."] },
  { id: "A46", pattern: "It is + adj. + for sb + to V", tags: ["it-pattern", "infinitive"], examples: ["It is easy for her to do the job.", "It is sad for me to hear the news."] },
  { id: "A47", pattern: "It is + adj. + of sb + to V", tags: ["it-pattern", "infinitive"], examples: ["It is kind of you to help me.", "It is nice of you to do this for me."] },
  { id: "A48", pattern: "It is + adj. + to V", tags: ["it-pattern", "infinitive"], examples: ["It is convenient to eat at a food stand.", "It is wrong to cheat on exams."] },
  { id: "A49", pattern: "It is no use + V-ing", tags: ["it-pattern", "gerund"], examples: ["It is no use pretending you didn't know.", "It's no use arguing with a drunk."] },
  { id: "A50", pattern: "It is said (that) + S + V", tags: ["it-pattern", "passive"], examples: ["It is said he's a genius.", "It is said that he was a spy during the war."] },
  { id: "A51", pattern: "It is time + S + 過去式", tags: ["subjunctive"], examples: ["It is time we were going.", "It is time we had a party."] },
  { id: "A52", pattern: "It is time (for sb) + to V", tags: ["infinitive"], examples: ["It is time (for us) to go home.", "It is time (for us) to clean it up."] },
  { id: "A53", pattern: "make + O + n. / adj.", tags: ["causative"], examples: ["His answer made me happy.", "I'll make him my servant."] },
  { id: "A54", pattern: "make + O + V", tags: ["causative"], examples: ["He made me drive the car.", "The teacher makes Jack clean the window."] },
  { id: "A55", pattern: "lest ... (should) + V", tags: ["subjunctive", "clause"], examples: ["He ran away lest he (should) be seen.", "She pulled away from the window lest anyone see them."] },
  { id: "A56", pattern: "N + V-ing ... (現在分詞修飾名詞)", tags: ["participle"], examples: ["She was the woman sitting behind me in the restaurant yesterday.", "It was a series of separate walls extending across northern China."] },
  { id: "A57", pattern: "need / want / require + V-ing", tags: ["gerund", "passive"], examples: ["The garden doesn't need watering.", "All cars require servicing regularly."] },
  { id: "A58", pattern: "neither ... nor ...", tags: ["conjunction"], examples: ["He neither knows nor cares what happened.", "The hotel is neither spacious nor comfortable."] },
  { id: "A59", pattern: "never ... but ... (沒有…而不)", tags: ["idiom"], examples: ["It never rains but it pours.", "I never came to the club but I met Tom."] },
  { id: "A60", pattern: "There is no + V-ing", tags: ["gerund", "idiom"], examples: ["There is no mistaking a tiger for a dog.", "There is no knowing how many people got killed in World War II."] },
  { id: "A61", pattern: "No matter what ...", tags: ["concession", "clause"], examples: ["No matter what he did, they were bored.", "No matter what you do, I'll always love you."] },
  { id: "A62", pattern: "No sooner had + S + V-en + than ...", tags: ["inversion", "time"], examples: ["No sooner had he arrived than he was asked to leave again.", "No sooner had he sat down than the phone rang."] },
  { id: "A63", pattern: "Not only ..., but (also) ...", tags: ["conjunction"], examples: ["He not only finished his homework in time but also enjoyed doing it.", "We go there not only in winter, but also in summer."] },
  { id: "A64", pattern: "Not + V-ing ..., S + V ... (否定分詞構句)", tags: ["participle"], examples: ["Not being tall enough, I stood on a chair to get it.", "Not knowing what to do, I hid myself under the bed."] },
  { id: "A65", pattern: "not ... until ...", tags: ["time"], examples: ["He didn't shut up until the teacher came in.", "He didn't get up until 8:00."] },
  { id: "A66", pattern: "Now that + S + V ...", tags: ["reason", "clause"], examples: ["Now that you are here, why not have a drink?", "Now that you have passed the test, you can drive on your own."] },
  { id: "A67", pattern: "Only when + S1 + V1 + aux + S2 + V2 (倒裝)", tags: ["inversion"], examples: ["Only when you really love someone can you know the power of love.", "Only when you see it can you believe it."] },
  { id: "A68", pattern: "Passive voice (被動語態)", tags: ["passive"], examples: ["Her leg was broken.", "He was bitten by a dog."] },
  { id: "A69", pattern: "Relative clauses (關係子句)", tags: ["clause"], examples: ["Marian is the teacher who teaches my son English.", "The girl who sits in the front row is from Japan."] },
  { id: "A70", pattern: "S + ask / want / tell / allow + sb + to V", tags: ["infinitive"], examples: ["I asked James to buy some bread.", "The boss doesn't allow me to use the telephone."] },
  { id: "A71", pattern: "S + aux + not + V + without + N / V-ing", tags: ["idiom"], examples: ["You can't leave the country without a passport.", "He couldn't live without her."] },
  { id: "A72", pattern: "S + be worth + V-ing / NP", tags: ["gerund"], examples: ["The book is worth reading.", "The picture is worth about two thousand pounds."] },
  { id: "A73", pattern: "S + cannot help + V-ing", tags: ["gerund", "idiom"], examples: ["He can't help having big ears.", "I couldn't help hearing what you just said."] },
  { id: "A74", pattern: "S + find / keep / catch + O + V-ing / p.p.", tags: ["participle"], examples: ["The lady kept the man waiting for a long time.", "You will find people walking faster and working harder in a big city."] },
  { id: "A75", pattern: "S + have no choice but to V", tags: ["idiom", "infinitive"], examples: ["They have no choice but to agree to what he suggested.", "He has no choice but to go home."] },
  { id: "A76", pattern: "S + have trouble / difficulty + (in) V-ing", tags: ["gerund"], examples: ["He has trouble in studying math.", "We have enough difficulty paying the rent as it is!"] },
  { id: "A77", pattern: "S + hear / see + O + V / V-ing", tags: ["perception"], examples: ["I saw a boy playing there.", "I saw Mrs. Smith singing."] },
  { id: "A78", pattern: "S + insist / advise + that + S + (should) + V", tags: ["subjunctive", "clause"], examples: ["The girl insisted that Vingo join them.", "We advised that they should start early."] },
  { id: "A79", pattern: "S + V + by + V-ing / N", tags: ["gerund"], examples: ["She earns her living by selling insurance.", "He was struck by lightning."] },
  { id: "A80", pattern: "S + V + wh-clause", tags: ["clause"], examples: ["I don't know where he lives.", "I couldn't hear what she said."] },
  { id: "A81", pattern: "S + V + 動名詞", tags: ["gerund"], examples: ["She enjoys playing tennis.", "She's never liked swimming."] },
  { id: "A82", pattern: "S + V ..., including + NP", tags: ["idiom"], examples: ["The price is $100, including postage and packing.", "Sales up to and including last month amounted to $100,000."] },
  { id: "A83", pattern: "S + V ..., unless + S + V ...", tags: ["conditional", "clause"], examples: ["You will never pass the exam unless you study hard.", "Kevin never tells a lie unless he is forced to."] },
  { id: "A84", pattern: "S1 + have + V1-en ... since + S2 + V2-ed", tags: ["tense", "time"], examples: ["Where have you been since I last saw you?", "It was the first time I'd won since I'd learnt to play chess."] },
  { id: "A85", pattern: "S1 + V1 + so + adj./adv. + that + S2 + V2", tags: ["result", "clause"], examples: ["He was so ill that we had to send for a doctor.", "She was so angry that she couldn't speak."] },
  { id: "A86", pattern: "See / Hear + O + V-ing", tags: ["perception"], examples: ["The soldiers could see the enemy coming from far away.", "We heard him playing the guitar."] },
  { id: "A87", pattern: "Should / Shouldn't + have + p.p.", tags: ["modal"], examples: ["You should have told me that before we left.", "Tom, you should have done your homework."] },
  { id: "A88", pattern: "so + adj./adv. + that ...", tags: ["result", "clause"], examples: ["It was so hot that I couldn't think clearly.", "She was so beautiful that every boy in the room kept looking at her."] },
  { id: "A89", pattern: "..., so that ... (表目的)", tags: ["purpose", "clause"], examples: ["You should take care of yourself so that you won't get sick.", "Use your time well so that you won't get behind in your studies."] },
  { id: "A90", pattern: "such ... that ...", tags: ["result", "clause"], examples: ["Work was such a deep pleasure for her that she never thought of stopping.", "It was such a good film that I saw it twice."] },
  { id: "A91", pattern: "so / neither 的倒裝", tags: ["inversion"], examples: ["He is divorced and so am I.", "He doesn't like Beethoven and neither do I."] },
  { id: "A92", pattern: "Some ... and some ...", tags: ["idiom"], examples: ["Some learn it faster and some slower.", "Some people traveled by car and some by train."] },
  { id: "A93", pattern: "stop + O + from + V-ing", tags: ["gerund"], examples: ["No one can stop me from going.", "I couldn't stop my body from shaking."] },
  { id: "A94", pattern: "..., such as ...", tags: ["idiom"], examples: ["Sports are good for the health, but some sports, such as motorcycle racing, can be dangerous.", "I like fruit such as apples and oranges."] },
  { id: "A95", pattern: "That's why / how ... + S + V", tags: ["clause"], examples: ["That's why you gave John so much money.", "That's how you finished doing your homework."] },
  { id: "A96", pattern: "The + 比較級 + S + V ..., the + 比較級 + S + V ...", tags: ["comparison"], examples: ["The more you eat, the fatter you will get.", "The longer you stay, the more you will have to pay."] },
  { id: "A97", pattern: "The imperative mood (祈使語氣)", tags: ["imperative"], examples: ["Be patient.", "Don't jump to conclusions."] },
  { id: "A98", pattern: "The past perfective (過去完成式)", tags: ["tense"], examples: ["The children had all gone to bed by ten o'clock last night.", "I found the watch that I had lost."] },
  { id: "A99", pattern: "The superlative construction (最高級)", tags: ["comparison"], examples: ["Susan is the shortest of the three.", "Cindy is the least heavy of the three."] },
  { id: "A100", pattern: "Those who ...", tags: ["clause"], examples: ["Those who expect the worst are less likely to be disappointed.", "Those who took up weapons to defend themselves are political prisoners."] },
  { id: "A101", pattern: "To + V ..., S + V (不定詞表目的)", tags: ["infinitive", "purpose"], examples: ["To get a good seat, she arrived early.", "To earn money, she's working hard."] },
  { id: "A102", pattern: "too ... to ...", tags: ["infinitive"], examples: ["The opportunity is too good to miss.", "Sue was too young to go to school."] },
  { id: "A103", pattern: "V + ... (祈使句)", tags: ["imperative"], examples: ["Stop talking!", "Go away!"] },
  { id: "A104", pattern: "V-ing ..., S + V (分詞構句)", tags: ["participle"], examples: ["A man sat under a tree, selling hats to passers-by.", "Picking up all the hats, the man went home happily."] },
  { id: "A105", pattern: "Wh- + to V", tags: ["infinitive"], examples: ["If you are not sure what to do, just ask.", "They showed her how to operate the faucet."] },
  { id: "A106", pattern: "When it comes to + NP / V-ing, S + V ...", tags: ["gerund", "idiom"], examples: ["I'm as good a cook as she is except when it comes to making pastry.", "I can use a computer, but when it comes to repairing them, I know nothing."] },
  { id: "A107", pattern: "Wherever / Whatever / However / Whenever + S1 + V1, S2 + V2", tags: ["concession", "clause"], examples: ["Whatever you like, you can eat.", "Wherever he is, I'll find him."] },
  { id: "A108", pattern: "Whether ... or ...", tags: ["clause"], examples: ["We were wondering whether to go today or tomorrow.", "To this day, it's unclear whether he shot himself or was murdered."] },
  { id: "A109", pattern: "would rather ... than ...", tags: ["comparison", "idiom"], examples: ["I would rather walk than take a bus.", "She'd rather die than lose the children."] },
  { id: "A110", pattern: "It is + adj. + that + S + (should) + V", tags: ["subjunctive", "it-pattern"], examples: ["It is important that he be on time.", "It is necessary that everyone attend the meeting."] },
];

export const ALL_SENTENCE_PATTERNS = [...SP_BASIC, ...SP_APPLIED];
export function patternsByTier(tier: "basic" | "applied"): SentencePattern[] {
  return tier === "basic" ? SP_BASIC : SP_APPLIED;
}
